#!/usr/bin/env bash

set -eo pipefail

DOTFILES_DIR=$(cd $(dirname $0) && pwd -P)

# .gitconfig
ln -sf ${DOTFILES_DIR}/.gitconfig ~/.gitconfig

# .gitignore_global
ln -sf ${DOTFILES_DIR}/.gitignore_global ~/.gitignore_global

# iterm
rm -rf ~/.iterm
ln -sf ${DOTFILES_DIR}/macos/.iterm ~/.iterm

# .bash_profile
ln -sf ${DOTFILES_DIR}/macos/.bash_profile ~/.bash_profile

# .bashrc
ln -sf ${DOTFILES_DIR}/macos/.bashrc ~/.bashrc

# .vimrc
ln -sf ${DOTFILES_DIR}/.vimrc ~/.vimrc

# .vim
rm -rf ~/.vim
ln -sf ${DOTFILES_DIR}/.vim ~/.vim

# karabiner
rm -rf ~/.config/karabiner
ln -sf ${DOTFILES_DIR}/macos/.config/karabiner ~/.config/karabiner

# vscode
mkdir -p ~/Library/Application\ Support/Code/User
ln -sf ${DOTFILES_DIR}/vscode/settings.json ~/Library/Application\ Support/Code/User/settings.json
ln -sf ${DOTFILES_DIR}/vscode/keybindings_macos.json ~/Library/Application\ Support/Code/User/keybindings.json

# MacOS Preferences
${DOTFILES_DIR}/macos/preferences.sh
