#!/usr/bin/env python3

import os
import json


def main() -> None:
    """Display the most recently used items"""

    history_file = os.path.join(
        os.path.dirname(__file__),
        ".history",
    )

    passwords = []

    with open(history_file, "r", encoding="utf-8") as f:
        for password in f:
            passwords.append(password.strip())

    print(
        json.dumps(
            {
                "items": [
                    {
                        "title": password,
                        "arg": password,
                    }
                    for password in reversed(passwords)
                ]
            }
        )
    )


if __name__ == "__main__":
    main()
