#!/usr/bin/env bash

set -eo pipefail

# General
brew install bash
brew install bash-completion

# Utilities
brew install htop
brew install jq

# Productivity
brew install --cask alfred
brew install --cask obsidian

# Dev tools
brew install git
brew install golang
brew install pyenv
brew install nvm
brew install direnv
brew install black
brew install shellcheck
brew install make
brew install rustup
brew install --cask docker
brew install --cask iterm2
brew install --cask visual-studio-code
brew install --cask zed

# Cloud tools
brew install kubectl
brew install awscli
brew install opentofu
brew install terraform-ls
brew install kubernetes-cli

# GPG tools
brew install gpg
brew install pinentry-mac

# Desktop utilities
brew install --cask hammerspoon
brew install --cask karabiner-elements
brew install --cask discord
brew install --cask jordanbaird-ice

# Cargo Addons
rustup toolchain install stable
cargo install cargo-edit
