#!/usr/bin/env zsh

set -eo pipefail

brew install iterm2
brew install --cask docker
brew install kubectl
brew install awscli
brew install pyenv
brew install karabiner-elements
brew install golang
brew install --cask discord
brew install --cask visual-studio-code
